[package]
name = "grimlet"
version = "0.1.0"
edition = "2024"

[[bin]]
name= "main"
path = "src/main.rs"


[[bin]]
name = "llvm_examples"
path = "src/llvm_examples.rs"

[dependencies]
anyhow = "1.0.100"
capstone = "0.13.0"
inkwell = { version = "0.6.0", features = ["llvm18-1"] }
