[package]
name = "emulator"
version = "0.1.0"
edition = "2024"

[dependencies]
anyhow = { workspace = true }
capstone = { workspace = true }
inkwell = { workspace = true, features = ["llvm18-1"] }

[dev-dependencies]
test_utils = { path = "../test_utils" }
